### ISSUE TITLE
Spec compliance: crash when adding user to ban list on dendrite

### ISSUE THREAD

**Issue by bones-was-here** [matrix-org/mjolnir#305]
**Describe the bug**
When the homeserver is Dendrite (tested version: c4df6d77231358f161e5243e62af6510258943a5),
when adding a user to a banlist, mjolnir crashes:
```
/data/home/mjolnir/mjolnir.git/lib/models/BanList.js:289
                 event.unsigned.rule = rule;
                                     ^
TypeError: Cannot set properties of undefined (setting 'rule')
    at BanList.<anonymous> (/data/home/mjolnir/mjolnir.git/lib/models/BanList.js:289:37)
    at Generator.next (<anonymous>)
    at fulfilled (/data/home/mjolnir/mjolnir.git/lib/models/BanList.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
And immediately crashes with the same message on subsequent startups, 
```
Error during startup:
TypeError: Cannot set properties of undefined (setting 'rule')
     at BanList.<anonymous> (/data/home/mjolnir/mjolnir.git/lib/models/BanList.js:289:37)
     at Generator.next (<anonymous>)
     at fulfilled (/data/home/mjolnir/mjolnir.git/lib/models/BanList.js:20:58)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
This appears to be because mjolnir assumes an optional key is populated: [dendrite#2521](https://github.com/matrix-org/dendrite/issues/2521)

**To Reproduce**
1. !mjolnir list create bl banlist
2. !mjolnir default bl
3. !mjolnir ban user @badguy:example.com

**Expected behavior**
It would not crash :)  and would not assume the unsigned key to be present, because the spec says it's optional.  

**Additional context**
Tested versions: 558cbb3caecde25d24f354dd5afa07af12891f06 bf7f1318af3ef057b67152e64cd553eb81494f93 1.4.2 1.3.2  
Built manually per: https://github.com/matrix-org/mjolnir/blob/main/docs/setup_selfbuild.md  
Node.js 16.15.1 LTS (nodesource package) on Debian 11.3

**Comment by Yoric** [comment]
Ouch. That's bad. I'll take a look.

**Comment by tux93** [comment]
Hey, I just ran into the same issue today and locally cherry-picking 8ce269c fixed it, would be nice if it got merged

**Comment by Gnuxie** [comment]
Should be fixed in #378

**Comment by bones-was-here** [comment]
I would like to test if this is resolved in 1.6.1 but it fails to start (after setting all the mjolnir state event contents to {} on its account so it should be "fresh"):

```
Mon, 28 Nov 2022 14:42:45 GMT [INFO] [index] Starting bot...
Mon, 28 Nov 2022 14:42:45 GMT [INFO] [index] Resolving management room...
Creating Web APIs
Mon, 28 Nov 2022 14:42:45 GMT [INFO] [index] Mjolnir is starting up. Use !mjolnir to query status.
Starting web server
Mon, 28 Nov 2022 14:42:45 GMT [INFO] [ProtectedRoomsConfig] Resolving protected rooms...
/data/home/mjolnir/mjolnir.git/lib/utils.js:32
    return input.replace(/["&<>]/g, (char) => ({
                 ^
TypeError: input.replace is not a function
    at htmlEscape (/data/home/mjolnir/mjolnir.git/lib/utils.js:32:18)
    at ManagementRoomOutput.logMessage (/data/home/mjolnir/mjolnir.git/lib/ManagementRoomOutput.js:102:56)
    at ProtectionManager.start (/data/home/mjolnir/mjolnir.git/lib/protections/ProtectionManager.js:66:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Mjolnir.start (/data/home/mjolnir/mjolnir.git/lib/Mjolnir.js:250:13)
    at async /data/home/mjolnir/mjolnir.git/lib/index.js:79:9
```

It prints 1 message to the management room before crashing:  
`Mjolnir is starting up. Use !mjolnir to query status.`

**Comment by tux93** [comment]
It's starting fine for me, however I'm seeing a handfull of `Cannot find state event for "org.matrix.mjolnir.setting"` errors in the Journal during startup, not sure if that is related to this ticket

**Comment by Gnuxie** [comment]
@tux93 those are normal but shouldn't be logged as ERROR in the first place

**Comment by turt2live** [comment]
I'm presuming this is fixed. If not, please open a new issue with fresh logs.
