### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/data/config/production.yaml'

### ISSUE THREAD

**Issue by minnixtx** [matrix-org/mjolnir#381]
Using docker compose, I've made the appropriate folder structure via the read me here https://github.com/matrix-org/mjolnir/blob/main/docs/setup_docker.md. In my home folder I created a mjolnir folder and inside that resides the docker-compose.yaml and a config folder which contains production.yaml. After executing 'docker compose up' I get the following:

```exited with code 1
mjolnir-mjolnir-1  | node:fs:594
mjolnir-mjolnir-1  |   handleErrorFromBinding(ctx);
mjolnir-mjolnir-1  |   ^
mjolnir-mjolnir-1  | 
mjolnir-mjolnir-1  | Error: ENOENT: no such file or directory, open '/data/config/production.yaml'
mjolnir-mjolnir-1  |     at Object.openSync (node:fs:594:3)
mjolnir-mjolnir-1  |     at Object.readFileSync (node:fs:462:35)
mjolnir-mjolnir-1  |     at read (/mjolnir/config.js:86:24)
mjolnir-mjolnir-1  |     at /mjolnir/index.js:25:38
mjolnir-mjolnir-1  |     at Object.<anonymous> (/mjolnir/index.js:63:3)
mjolnir-mjolnir-1  |     at Module._compile (node:internal/modules/cjs/loader:1126:14)
mjolnir-mjolnir-1  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
mjolnir-mjolnir-1  |     at Module.load (node:internal/modules/cjs/loader:1004:32)
mjolnir-mjolnir-1  |     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
mjolnir-mjolnir-1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
mjolnir-mjolnir-1  |   errno: -2,
mjolnir-mjolnir-1  |   syscall: 'open',
mjolnir-mjolnir-1  |   code: 'ENOENT',
mjolnir-mjolnir-1  |   path: '/data/config/production.yaml'
mjolnir-mjolnir-1  | }
```

**Comment by minnixtx** [comment]
Thanks to mahdi in the matrix room for listing the exact structure. For anyone else it is like this:

```mjolnir
├── docker-compose.yml
└── mjolnir
    ├── config
    │   └── production.yaml
    └── storage
        └── bot.json
```
