### ISSUE TITLE
TypeError: Utils.isRegExp is not a function

### ISSUE THREAD

**Issue by reeseovine** [matrix-org/mjolnir#552]
No matter how I try to run mjolnir, it always seems to fail right away with this error message:

```text
/opt/mjolnir/node_modules/config/lib/config.js:1006
    } else if (Utils.isRegExp(parent)) {
                     ^

TypeError: Utils.isRegExp is not a function
    at _clone (/opt/mjolnir/node_modules/config/lib/config.js:1006:22)
    at Config.cloneDeep (/opt/mjolnir/node_modules/config/lib/config.js:1046:10)
    at /opt/mjolnir/node_modules/config/lib/config.js:1318:32
    at Array.forEach (<anonymous>)
    at util.extendDeep (/opt/mjolnir/node_modules/config/lib/config.js:1293:9)
    at /opt/mjolnir/node_modules/config/lib/config.js:651:12
    at Array.forEach (<anonymous>)
    at util.loadFileConfigs (/opt/mjolnir/node_modules/config/lib/config.js:648:16)
    at new Config (/opt/mjolnir/node_modules/config/lib/config.js:113:27)
    at Object.<anonymous> (/opt/mjolnir/node_modules/config/lib/config.js:1510:31)

Node.js v23.0.0
```

This is on `v1.8.0` as well as `main`

Invocations I've tried:

- `node lib/index.js --mjolnir-config ./config/production.yaml`
- `/usr/bin/node /opt/mjolnir/lib/index.js --mjolnir-config /opt/mjolnir/config/production.yaml`
- `yarn run start:dev --mjolnir-config /opt/mjolnir/config/production.yaml`

**Comment by arjan-s** [comment]
Same here on `1.8.3` (the latest release atm). In my case it was caused by upgrading nodejs from (`22.10.0-1` -> `23.1.0-1`). Downgrading nodejs again fixed the issue (temporarily obviously).
